### ISSUE TITLE
Should be portable

### ISSUE THREAD

**Issue by mattmcnabb** [mattmcnabb/O365Admin#1]
This module should be portable and not require any of the external modules such as LyncOnlineConnector, Microsoft.Online.Sharepoint.Powershell, or the Sign-In Assistant.

**Comment by mattmcnabb** [comment]
I have been able to demonstrate packaging the Lync, MSOL, and Sharepoint modules within this module, but so far cannot get around the dependency on the Microsoft Online Services Sign-In Assistant. This seems to be because it requires registration in the GAC. Maybe I'll figure out how to get around that...

**Comment by kjacobsen** [comment]
I would actually opt to leave the Microsoft modules separately. It is totally fine to have those modules as a dependency.

**Comment by mattmcnabb** [comment]
Kieran: Thanks for the input. Don't you think it would be nice to be able to download this module and connect to any of the Office 365 services without having to download all the dependencies? I suggested this as an issue because I've always wondered why Microsoft has not provided a unified module yet.

It could also help prevent issues that may crop up in the code if an updated module from Microsoft breaks something in the module.

**Comment by kjacobsen** [comment]
There are a few reasons for the lack of a unified module. The biggest is the fact that 3/4 distinct teams are maintaining the three modules:
1. Exchange is standalone/portable as is, after all we just establish a PS-Session
2. MSOL Module is maintained between the Office 365 and Azure AD Teams
3. Lync Online is a bit of a mess right now, but getting better. 

What would be the legal implications of trying to bundle Microsoft's Code? It might be worth checking on this one!

From a design point of view, I have actually kept my own Exchange / MSOL / Lync modules separate to ensure I can reduce complexity.

**Comment by mattmcnabb** [comment]
Closing issue as this is probably an unrealistic goal. Azure AD would not work due to requiring the Sign-in Assistant which is a Windows service.
